TechGroup02/FrancoAldunate/TicTacToe
jlopezbotas/TechGroup02 pull request #15
Opened 2019-10-09 03:03 UTC by FrancoDaniel14

2019-10-09 03:53 UTC, FrancoDaniel14 commented
![image](https://user-images.githubusercontent.com/28268318/66450509-cf5ac500-ea26-11e9-9de8-7f0e3b6732f4.png)

2019-10-15 00:01 UTC, devidnet requested changes

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/test/TicTacToeTest.java
> +        final String expectedResult = "X";
Invalid player selection (3 or more) should not return a valid player mark (X or O), it is not optimal to validate and limit the number of players.

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/test/TicTacToeTest.java
> +        ticTacToe.setStartPlayer(2);
Set up a start player could be by passing directly the mark, not a number, or if the game could planned to allow other players as well, a pair id player and mark assignation can be passed to this method

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/test/TicTacToeTest.java
> +        final String[][] board = new String[][]{{"-", "-", "-"}, {"-", "X", "-",}, {"-", "-", "-"}};
Unit test might not be depended on previous unit tests

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/test/TicTacToeTest.java
> +    public void getBoardPositionWithValidValueTestReturnsArrayOfEquivalentMatrixPosition() {
Too long name

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/test/TicTacToeTest.java
> +        assertArrayEquals(expectedResult, actualResult);
You are testing only one position

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/test/TicTacToeTest.java
> +        assertFalse(actualResult);
Seems to be E2E testing, You probably can start with a full board variable

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/tic_tac_toe/Main.java
> +        boolean isActive = true;
Probably it will be more understandable variable name isGameActive

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/tic_tac_toe/TicTacToe.java
> +    private static final String X_SYMBOL = "X";
It would be preferable to use char type

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/tic_tac_toe/TicTacToe.java
> +    public String setStartPlayer(final int number) {
If default player is X no need to choose between two player numbers

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/tic_tac_toe/TicTacToe.java
> +        }
Apply ternary condition

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/tic_tac_toe/TicTacToe.java
> +    public int[] getBoardPosition(final int position) {
Do you consider a bigger table, this way is not optimal

2019-10-15 00:01 UTC, devidnet commented on FrancoAldunate/TicTacToe/src/test/TicTacToeTest.java
> +        final int[] actualResult = ticTacToe.getBoardPosition(0);
You could pass an array of invalid position and iterate on it

2019-10-17 04:33 UTC, closed without merging